#!/usr/bin/env bash
# A script that takes a subdomain and domain and returns information about the subdomain

print_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "501125-lb-01.$1" "501125-lb-01"
    print_info "501125-web-01.$1" "501125-web-01"
    print_info "501125-web-02.$1" "501125-web-02"
fi
