#!/usr/bin/env bash
# File to install Nginx with below config:
#+    will listen on port 80.
#+    will return page containing "Hello World" when queried
#+    at the root using a curl GET request.
#+    will configure /redirect_me as a "301 Moved Permanently".
#+    will include a custom 404 page containing "Ceci n'est pas une page".
#+    will contain a custom HTTP header named X-Served-By.
#+    value of the HTTP header is the hostname of running server.

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
