#!/usr/bin/env bash
# A script that manages the script manage_my_process.
#   When passed the argument `start`:
#     will Start manage_my_process
#     will Creates a file containings its PID in /var/run/my_process.pid
#     will display "manage_my_process started"
#   When passed the argument `stop`:
#     Stop manage_my_process
#     delete the file /var/run/my_process.pid
#     display "manage_my_process stopped"
#   When passed the argument `restart`:
#     will stop manage_my_process
#     will delete the file /var/run/my_process.pid
#     will start manage_my_process
#     will create a file containing its PID in /var/run/my_process.pid
#     will display "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
