#!/usr/bin/env bash
# A Bash script to display the content of the /etc/passwd
# but only username, user id, user home directory path

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
