#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 and
# displays "bad luck from China" on the 4th iteration
# displays "bad luck from Japan" on the 9th iteration
# displays "bad luck from Italy" on the 17th loop iteration

count_number=1

while [ $count_number -le 20 ]
do
  echo "$count_number"
  case $count_number in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count_number++ ))
done
