#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes.
# It will display hours from 0 to 12 and
# minutes from 1 to 59

hour_time=0

while [ $hour_time -le 12 ]
do
  echo "Hour: $hour_time"
minute_time=1
  while [ $minute_time -le 59 ]
  do
    echo "$minute_time"
    (( minute_time++ ))
  done
  (( hour_time++ ))
done
