#!/usr/bin/env bash
# A script to configure a ufw firewall
#+ it will block all incoming traffic except
#+ TCP port 22, TCP port 443 and TCP port 80.

sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
