#!/usr/bin/env bash
# Script to put the following configuration in an Ubuntu server
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.working
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.working
cp -f ~/hosts.working /etc/hosts
